- hosts: all
  user: vagrant
  tasks:
    - name: update apt
      apt: update_cache=yes

    - name: Essentials
      apt: pkg=$item state=latest
      with_items:
        - python-software-properties
        - python-setuptools

    - name: Install pip
      easy_install: name=pip
    - name: Install postgres 9.1
      apt: pkg=postgresql state=latest

    - name: Install postgres 9.1 (dev)
      apt: pkg=postgresql-server-dev-9.1 state=latest

    - name: Postgres contrib for hstore
      apt: pkg=postgresql-contrib state=latest

    ###
    # Postgis
    ###
    - name: install postgis deps
      apt: pkg=$item state=latest
      with_items:
        - build-essential
        - libxml2-dev
        - libgeos-dev
        - libproj-dev
        - libgdal1-dev
        - libpq-dev
        - python-dev

    - name: Install postgres driver for python
      pip: name=psycopg2

    - name: Create download dir
      file: dest=/usr/local/postgis/download owner=vagrant state=directory

    - name: Download PostGis
      action: get_url url=http://download.osgeo.org/postgis/source/postgis-2.0.1.tar.gz
                  dest=/usr/local/postgis/download/postgis-2.0.1.tar.gz mode=0440

    - name: Untar PostGis
      command: tar xzf postgis-2.0.1.tar.gz
               chdir=/usr/local/postgis/download/
               creates=/usr/local/postgis/download/postgis-2.0.1

    - name: Install PostGis
      command: $item
               chdir=/usr/local/postgis/download/postgis-2.0.1
               creates=/usr/share/postgresql/9.1/extension/postgis--2.0.1.sql
      with_items:
        - ./configure --without-topology
        - make
        - make install

    - name: make sure postgres is going
      service: name=postgresql state=running


    ###
    # Init users and databases
    ###
    - name: Create user
      sudo: True
      sudo_user: postgres
      postgresql_user: name=amtrak password=amtrak
      register: last_result

    - name: Create database
      sudo: True
      sudo_user: postgres
      postgresql_db: name=amtrak owner=amtrak
      register: last_result

    - name: Add PostGIS Extension
      sudo: True
      sudo_user: postgres
      command: psql amtrak -c "CREATE EXTENSION IF NOT EXISTS postgis"
